version: "3.9"
services:
  api:
    build: .
    env_file: .env
    volumes:
      - ./chroma_store:/app/chroma_store
      - ./app.db:/app/app.db
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload